efault: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Aa@123456
  host: localhost

development:
  <<: *default
  database: store_flower
test:
  <<: *default
  database: store_flower_test

production:
  <<: *default
  database: store_flower_production
  username: store_flower
  password: <%= ENV['STORE_FLOWER_DATABASE_PASSWORD'] %>
